version: '3'

services:
  db:
    image: postgres@sha256:322e9d80bbe0d19df45a2cfa262b50947683b4da283afdb6bee8e549aea87bf3
    container_name: pmc-wiki-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ZKd7PYRc3RjYXCTd7fSUxAbzlq8JqVpz
    logging:
      options:
        max-file: 3
        max-size: 10m
  main:
    image: requarks/wiki@sha256:de23673914e56b69b795987509ca8e5f45aa6ca3834ae91e57b55e5388d3d4e3
    container_name: pmc-wiki-main
    volumes:
      - ${PWD}/config.yml:/wiki/config.yml:ro
    logging:
      options:
        max-file: 3
        max-size: 10m
    ports:
      - 8002:3000
    restart: always
